server:
  port: 8081
spring:
    redis:
      host: 111.230.175.254
      password: 930722Jy!@#
      port: 6379
      pool:
          maxActive: 300
          maxIdle: 100
          maxWait: 1000
          timeout: 2000

    rabbitmq:
      host: 111.230.175.254
      port: 5672
      username: jingyang
      password: 930722Jy



